baseURL: 'https://notatkideva.pl/'
languageCode: 'pl-pl'
title: 'Notatki Deva'

sectionPagesMenu: ''

disqusShortname: 'notatkideva'
googleAnalytics: 'UA-8284530-15'

disableKinds: [section, taxonomy]
ignoreErrors: ["error-disable-taxonomy"]

params:
    subtitle: 'Trochę kodu, trochę gadania'

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

paginate: 5

related:
    includeNewer: true
    indices:
        - name: series
          weight: 200
        - name: categories
          weight: 50
        - name: tags
          weight: 100
        - name: date
          weight: 10
    threshold: 80
    toLower: false

privacy:
    googleAnalytics:
        anonymizeIP: true
        respectDoNotTrack: true

permalinks:
    /: '/:slug'
    posts: '/:year/:month/:slug'
    pages: '/:slug'
