baseURL: 'https://notatkideva.pl/'
languageCode: 'pl-pl'
title: 'Notatki Deva'

sectionPagesMenu: ''

disableKinds: []
ignoreErrors: ["error-disable-taxonomy"]

params:
    subtitle: 'Trochę kodu, trochę gadania'
    cloudflareAnalytics: '851dedc44ffb4d81b752da8eacff79d3'

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

paginate: 5
removePathAccents: true

related:
    includeNewer: true
    indices:
        - name: series
          weight: 200
        - name: categories
          weight: 80
        - name: tags
          weight: 80
    threshold: 80
    toLower: false

permalinks:
    /: '/:slug'
    posts: '/:year/:month/:slug'
    pages: '/:slug'
